# Generated by Django 3.2.6 on 2021-08-27 09:56

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('google_places_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Google places id')),
                ('street_address1', models.CharField(blank=True, max_length=80, null=True, verbose_name='Street address1')),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Street address2')),
                ('town_or_city', models.CharField(blank=True, max_length=40, null=True, verbose_name='Town or city')),
                ('county', models.CharField(blank=True, max_length=80, null=True, verbose_name='County')),
                ('postcode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postcode')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Country')),
                ('foreign_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Location homepage')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact email')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Event Title')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='Event URL')),
                ('description_short', models.CharField(max_length=280, verbose_name='Tweetable Description')),
                ('description_long', models.TextField(verbose_name='Text Description')),
                ('description_host', models.CharField(max_length=560, verbose_name='Host name and info')),
                ('date_start', models.DateTimeField(verbose_name='Event Start')),
                ('date_end', models.DateTimeField(verbose_name='Event End')),
                ('foreign_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='Event homepage')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Opener Image')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL to Image')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('host', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.location')),
            ],
        ),
    ]
