# Generated by Django 3.2.6 on 2021-09-09 16:16

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_location_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name', unique_with=('owner',), verbose_name='Location URL'),
            preserve_default=False,
        ),
    ]
