# Generated by Django 3.2.6 on 2021-09-29 13:54

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', verbose_name='Location URL'),
        ),
    ]
