# Generated by Django 3.2.6 on 2021-08-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210826_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='can_host',
            field=models.BooleanField(default=False, verbose_name='Can host events'),
        ),
    ]
