# Generated by Django 3.2.6 on 2021-09-21 12:18

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_number', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Order id')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='uuid', unique=True, verbose_name='Order URL')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Phone number')),
                ('street_address1', models.CharField(max_length=80, verbose_name='Street address1')),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True, verbose_name='Street address2')),
                ('town_or_city', models.CharField(max_length=40, verbose_name='Town or city')),
                ('county', models.CharField(blank=True, max_length=80, null=True, verbose_name='County')),
                ('postcode', models.CharField(max_length=20, verbose_name='Postcode')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('original_cart', models.TextField(default='')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('status_change', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('abort', 'Abort')], default='pending', max_length=7, verbose_name='Order status')),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('price_net', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Price, net')),
                ('tax_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Tax')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='checkout.order')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='tickets.tickettype')),
            ],
        ),
    ]
