# Generated by Django 3.2.6 on 2021-09-24 09:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20210921_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='uuid_as_str', verbose_name='Ticket URL'),
        ),
    ]
